"""auto_202604191444

Revision ID: 126d458ee54f
Revises: f5198420ab45
Create Date: 2026-04-19 14:44:26.349389

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "126d458ee54f"
down_revision: Union[str, Sequence[str], None] = "f5198420ab45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feed", "author")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feed", sa.Column("author", sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
