"""create feed tables

Revision ID: 3c874699ee06
Revises:
Create Date: 2026-04-19 11:10:56.204738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3c874699ee06"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feed",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("link", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column(
            "author", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column("summary", sa.TEXT(), nullable=True),
        sa.Column("published", sa.DateTime(), nullable=False),
        sa.Column("is_sent", sa.Boolean(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feedsource",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedsource")
    op.drop_table("feed")
    # ### end Alembic commands ###
