"""auto_202604211540

Revision ID: 5030a9bbe712
Revises: 89e2d5002759
Create Date: 2026-04-21 15:40:18.660511

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5030a9bbe712"
down_revision: Union[str, Sequence[str], None] = "89e2d5002759"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feedsource",
        sa.Column(
            "sync_status",
            sa.Enum(
                "PENDING", "RUNNING", "SUCCESS", "FAILED", "UNSET", name="taskstatus"
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "feedsource",
        sa.Column(
            "sync_msg", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feedsource", "sync_msg")
    op.drop_column("feedsource", "sync_status")
    # ### end Alembic commands ###
