"""auto_202604272058

Revision ID: 65f588149709
Revises: a85e4c031e55
Create Date: 2026-04-27 20:58:20.577720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f588149709'
down_revision: Union[str, Sequence[str], None] = 'a85e4c031e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('content', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'content')
    # ### end Alembic commands ###
