"""auto_202604272058

Revision ID: 9ae2e20696c4
Revises: 65f588149709
Create Date: 2026-04-27 20:58:51.224509

"""

from typing import Sequence, Union

from alembic import op

from app.db.session import DatabaseSession
from app.models.feed import Feed


# revision identifiers, used by Alembic.
revision: str = '9ae2e20696c4'
down_revision: Union[str, Sequence[str], None] = '65f588149709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    async def migrate(conn):
        async with DatabaseSession(bind=conn, expire_on_commit=False) as db:
            stmt = db.dialect.update(Feed).values(content=Feed.summary)
            await db.execute(stmt)
            await db.commit()

            stmt = db.dialect.update(Feed).values(summary=Feed.ai_summary)
            await db.execute(stmt)
            await db.commit()

    op.run_async(migrate)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
