"""auto_202604252049

Revision ID: a85e4c031e55
Revises: 5030a9bbe712
Create Date: 2026-04-25 20:49:21.292763

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85e4c031e55'
down_revision: Union[str, Sequence[str], None] = '5030a9bbe712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('ai_summary', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'ai_summary')
    # ### end Alembic commands ###
