"""auto_202604272115

Revision ID: f2a8d375276d
Revises: 9ae2e20696c4
Create Date: 2026-04-27 21:15:49.208129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a8d375276d'
down_revision: Union[str, Sequence[str], None] = '9ae2e20696c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('cover_url', sa.TEXT(), nullable=True))
    op.drop_column('feed', 'ai_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('ai_summary', sa.TEXT(), nullable=True))
    op.drop_column('feed', 'cover_url')
    # ### end Alembic commands ###
