"""add source id for feed

Revision ID: fc0c4a75dc7b
Revises: 3c874699ee06
Create Date: 2026-04-19 11:43:57.899538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0c4a75dc7b'
down_revision: Union[str, Sequence[str], None] = '3c874699ee06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('source_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_feed_source_id'), 'feed', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_source_id'), table_name='feed')
    op.drop_column('feed', 'source_id')
    # ### end Alembic commands ###
