"""auto_202604191932

Revision ID: 89e2d5002759
Revises: 126d458ee54f
Create Date: 2026-04-19 19:32:53.745574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '89e2d5002759'
down_revision: Union[str, Sequence[str], None] = '126d458ee54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedsource', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedsource', 'description')
    # ### end Alembic commands ###
