"""auto_202604191442

Revision ID: f5198420ab45
Revises: fc0c4a75dc7b
Create Date: 2026-04-19 14:42:21.360841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f5198420ab45'
down_revision: Union[str, Sequence[str], None] = 'fc0c4a75dc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('content', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
